### ISSUE TITLE
Не отрабатывает строка выполнения коммита

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-unpack#9]
Добрый день, исполняю скрипт синхронизации с хранилищем. 
Все проходит хорошо. Файлы добавляются, но строка:
"C:\Program Files (x86)\Git\bin\git.exe" commit -a --file="G:\Programes\TeamCity\buildAgent\temp\buildTmp\v8up_.txt" --author="viskvortsov <viskvortsov@vashkpi.ru>" >G:\Programes\TeamCity\buildAgent\temp\buildTmp\v8up_2.log
не отрабатывает.

При этом, если запускать ее интерактивно, то все проходит нормально.
В чем могут быть причины?

**Comment by 0xporky** [comment]
@viskvortsov А скрипт синхронизации с хранилищем вы чем запускаете (Jenkins?)?

**Comment by viskvortsov** [comment]
Teamcity

**Comment by 0xporky** [comment]
@viskvortsov Возможно проблемы в пользователе, под которым работает Teamcity.

**Comment by viskvortsov** [comment]
Действительно, сменил пользователя - заработало.
Спасибо!
